use std::fmt;
use thiserror::Error;

/// Errors thrown by the serde integration.
#[derive(Debug, Error)]
pub enum Error {
    /// Error generated by the serializer or deserializer.
    #[error("{0}")]
    Message(String),

    /// Error generated by the binary reader or writer.
    #[error(transparent)]
    Binary(#[from] crate::BinaryError),
}

impl serde_core::ser::Error for Error {
    #[cold]
    fn custom<T: fmt::Display>(msg: T) -> Self {
        Self::Message(msg.to_string())
    }
}

impl serde_core::de::Error for Error {
    #[cold]
    fn custom<T: fmt::Display>(msg: T) -> Self {
        Self::Message(msg.to_string())
    }
}
